config/routes.rb
Rails.application.routes.draw do
  get 'events/index'
  get 'events/secret'

  root 'events#index'
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :events
  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord
    belongs_to :user
	belongs_to :event
    # validates :name, length: { minimum: 2 }
    # validates :bio, length: { maximum: 500 }
    # validates :password, length: { in: 6..20 }
    # validates :registration_number, length: { is: 6 } 
end

app/models/event.rb
class Event < ApplicationRecord
    belongs_to :admin, class_name: "User"
    validates :start_date, presence: true
    validates :duration, presence: true, numericality: { greater_than: 0 }
    validates :title, presence: true, length: 5..140
    validates :description, presence: true, length: 20..1000
    validates :price, presence: true, inclusion: { in: 1..1000}
    validates :location, presence: true
    
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
	has_many :attendances  
	has_many :events, through: :attendances
    has_many :events, foreign_key: 'admin_id', class_name: "Event"
  

    after_create :welcome_send

    def welcome_send 
        UserMailer.welcome_email(self).deliver_now
    end 
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @events = Event.all
  end


  def show
    @event = Event.find(params[:id])
  end

  def secret
  
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def index
        @users = User.all
    end 
  
    def show
        @user = User.find_by(id: session[:user_id])  
    end

end
  

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/index.html.erb
<h1> Bienvenue </h1>
<h1>Liste des évènements</h1>
<div class="row">
<% @events.each do |event| %>  
  <div class="col-sm-6">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title"><%= event.title %></h5>
        <p class="card-text"><%= event.description %></p>
        <p class="card-text">created by : <%= event.admin.first_name %><%= event.admin.last_name %></p>
        <button type="button" class="btn btn-warning"><%= link_to "show", event%></button>       
        </div>
    </div>
  </div>
  <% end %>
</div>

app/views/events/secret.html.erb
<h1>Events#secret</h1>
<p>Find me in app/views/events/secret.html.erb</p>

app/views/events/show.html.erb
<div class="container">
  <p>
    <h2><%= @event.title%></h2>
  </p>
  <p>
    <h3><%= @event.description%></h3>
  </p>

<button type="button" class="btn btn-warning"><%= link_to 'Edit', edit_event_path(@event)  %></button>
<a href="<%= event_path(@event.id)%> class="btn btn-warning" class="btn btn-danger" data-confirm="êtes vous sur?" data-method="DELETE" >Supprimer</a>

</div>

<p>views/events/show</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Eventbright</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>


    
  </head>

  


  <header>
      <nav class="navbar navbar-expand-lg" style="background-color: #d4e0ce;">
        <a class="nav-link"><%= link_to "Accueil", events_index_path %></a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto"> 

            <% if user_signed_in? %>
            <li class="nav-item active">
              <div class="nav-link"><%= link_to "Mon profil", user_path(current_user) %></div> 
            </li>
            <li class="nav-item active">
            <div class="nav-link"><%= link_to "Créer un évènement", new_event_path %></div> 
            </li>
            <li class="nav-item">
              <div class="nav-link"><%= link_to "Déconnexion", destroy_user_session_path, method: :delete%></div> 
            </li>
          <%else%>
                <li class="nav-item">
                  <div class="nav-link"><%= link_to "S'inscrire", new_user_registration_path %></div> 
                </li>
                <li class="nav-item">
                  <div class="nav-link"><%= link_to "Se connecter", new_user_session_path%></div> 
                </li>
              <% end %>
              </ul>
          </div>
      </nav>
  </header>
  <body>

  <%= yield %>
  </body>
</html>

app/views/users/show.html.erb
<ul>
  <% if user_signed_in? %>
    <li>
      <%= link_to "Se deconnecter", destroy_user_session_path, method: :delete %>
    </li>

    <li>
      Votre email : <%= current_user.email %>
    </li>

    <li>
      <%= link_to "Modifier: votre email / votre mot de passe", edit_user_registration_path %>
    </li>

  <% else %>
    <li>    
      <%= link_to "Sign in", new_user_session_path %>
    </li>

    <li>
      <%= link_to "Sign up", new_user_registration_path %>
    </li>

  <% end %>
</ul>